const { api, errorResponse } = require("../../app")
const { body }               = require("../../autoapi")
const middlewares            = require("../../middlewares/users")
const AuthSchema             = require("../../schemas/auth")
const UserSchema             = require("../../schemas/users")
const EmailSchema            = require("../../schemas/emails")
const JWTAuth                = require("../../service/JWTAuth")
const UserController         = require("./users")
const EmailController        = require("./emails")

